### ISSUE TITLE
issues with python 3.7.2

### ISSUE THREAD

**Issue by kitten77** [aranair/rtscli#2]
Error:
```python
(urwid_ex) muad@debian:~/workbench/curses/rtscli$ rtscli
Traceback (most recent call last):
  File "/home/muad/venv/urwid_ex/bin/rtscli", line 11, in <module>
    load_entry_point('rtscli', 'console_scripts', 'rtscli')()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/muad/workbench/curses/rtscli/rtscli.py", line 2, in <module>
    from urllib import urlopen
ImportError: cannot import name 'urlopen' from 'urllib' (/usr/local/lib/python3.7/urllib/__init__.py)
``` 
Solved with:
```python
from urllib.request import urlopen
```   
Error:
```Python
(urwid_ex) muad@debian:~/workbench/curses/rtscli$ rtscli
Traceback (most recent call last):
  File "/home/muad/venv/urwid_ex/bin/rtscli", line 11, in <module>
    load_entry_point('rtscli', 'console_scripts', 'rtscli')()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/muad/workbench/curses/rtscli/rtscli.py", line 3, in <module>
    from HTMLParser import HTMLParser
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/HTMLParser.py", line 11, in <module>
    import markupbase
ModuleNotFoundError: No module named 'markupbase'
```  

Solved by:
```Python
from html.parser import HTMLParser
```   
Error:
```Python
Traceback (most recent call last):
  File "/home/muad/venv/urwid_ex/bin/rtscli", line 11, in <module>
    load_entry_point('rtscli', 'console_scripts', 'rtscli')()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/muad/workbench/curses/rtscli/rtscli.py", line 25
    palette = [
```
Solved by:
```Python
# Set up color scheme
- palette = [
-    ('titlebar', 'dark red', ''),
-    ('refresh button', 'dark green,bold', ''),
-    ('quit button', 'dark red', ''),
-    ('getting quote', 'dark blue', ''),

+#palette = [
+   #('titlebar', 'dark red', ''),
+    #('refresh button', 'dark green,bold', ''),
+   #('quit button', 'dark red', ''),
+    #('getting quote', 'dark blue', ''),
```
You have double set of these added to you code  
Error:
```Python
(urwid_ex) muad@debian:~/workbench/curses/rtscli$ rtscli
Traceback (most recent call last):
  File "/home/muad/venv/urwid_ex/bin/rtscli", line 11, in <module>
    load_entry_point('rtscli', 'console_scripts', 'rtscli')()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/muad/workbench/curses/rtscli/rtscli.py", line 5, in <module>
    import thread, logging
ModuleNotFoundError: No module named 'thread'
``` 
Solved by
```Python
import _thread
```  
Error:
```Python
(urwid_ex) muad@debian:~/workbench/curses/rtscli$ rtscli
Traceback (most recent call last):
  File "/home/muad/venv/urwid_ex/bin/rtscli", line 11, in <module>
    load_entry_point('rtscli', 'console_scripts', 'rtscli')()
  File "/home/muad/workbench/curses/rtscli/rtscli.py", line 143, in cli
    main_loop.run()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/main_loop.py", line 821, in _loop
    alarm_callback()
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/main_loop.py", line 172, in cb
    callback(self, user_data)
  File "/home/muad/workbench/curses/rtscli/rtscli.py", line 136, in refresh
    quote_box.base_widget.set_text(get_update())
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/widget.py", line 876, in set_text
    self._text, self._attrib = decompose_tagmarkup(markup)
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/util.py", line 377, in decompose_tagmarkup
    tl, al = _tagmarkup_recurse(tm, None)
  File "/home/muad/venv/urwid_ex/lib/python3.7/site-packages/urwid/util.py", line 418, in _tagmarkup_recurse
    raise TagMarkupException("Invalid markup element: %r" % tm)
urwid.util.TagMarkupException: Invalid markup element: None
```
Solved by:
```Python

def get_update():
    ticker_syms = [t[1] for t in tickers]
    try:
        results = loads(urlopen('https://www.google.com/finance/info?q=' + ",".join(ticker_syms)).read()[3:])
    except:
       - return 
       +return "we have a error returns a None value! which urwid do not like"
```
It now runs on python 3.7.2 but has no stock updates, that i haven't fixed

**Comment by aranair** [comment]
Unfortunately that's because google finance now blocks everyone lol. I've just switched it to use alphavantage.co which has a free API but ... more limited / throttled tho.

Also, I believe the urlopen should be fixed too.
