### ISSUE TITLE
Unable to run on Windows 10

### ISSUE THREAD

**Issue by gentleadam** [aranair/rtscli#5]
Seems I am unable to run this in Windows. Apparently fcntl doesn't exist in Windows. 

```
C:\Temp>rtscli
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python37-32\Scripts\rtscli-script.py", line 11, in <module>
    load_entry_point('rtscli==0.4.3', 'console_scripts', 'rtscli')()
  File "c:\users\adam\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\adam\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "c:\users\adam\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "c:\users\adam\appdata\local\programs\python\python37-32\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\adam\appdata\local\programs\python\python37-32\lib\site-packages\rtscli.py", line 145, in <module>
    main_loop = urwid.MainLoop(layout, palette, unhandled_input=handle_input)
  File "c:\users\adam\appdata\local\programs\python\python37-32\lib\site-packages\urwid\main_loop.py", line 115, in __init__
    screen = raw_display.Screen()
  File "c:\users\adam\appdata\local\programs\python\python37-32\lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined
```

**Comment by gentleadam** [comment]
Appears this issue is related to urwid - https://github.com/urwid/urwid/issues/240
